name: "release"

on:
  push:
    branches: [beta, alpha, master]

jobs:
  check:
    uses: vodyani/workflows/.github/workflows/check.yml@master
    with:
      enable_test: true

  semantic_release:
    uses: vodyani/workflows/.github/workflows/semantic-release-project.yml@master
    secrets:
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      enable_build: false
